### ISSUE TITLE
Finish docs for dry-validation

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-rb.org#2]
### TODO
- [x] add a section about predicate logic
- [x] add a section about macros
- [x] add a section about `option` + `with` APIs
- [ ] add a section about using constrained types for reusing validation rules
- [ ] add predicate usage examples
