### ISSUE TITLE
Improve dry-container docs

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-rb.org#92]
Right now it's a copy/paste from original README. It would be good to split it up into sub-sections and provide more info and context.
### TODO
- [ ] Improve intro section, explain the differences between dry-rb solution and heavy IoC frameworks
- [ ] Explain how it's used along with dry-auto_inject and dry-component, add links to example apps
- [ ] Split it into smaller sections
- [ ] Add a sub-section about stubbing, explain best practices, dos and donts etc.
