### ISSUE TITLE
dry-auto_inject needs new docs

### ISSUE THREAD

**Issue by solnic** [dry-rb/dry-rb.org#96]
We have a bunch of nice features that are completely undocumented :(

### TODO

- [ ] document how to create a custom injector with options
- [ ] document `kwargs` strategy
- [ ] document `*args` strategy
- [ ] point to dry-system

**Comment by timriley** [comment]
> document how to create a custom injector with options

What did you mean by this, @solnic?

**Comment by solnic** [comment]
>> document how to create a custom injector with options
> What did you mean by this, @solnic?

This could be skipped (unless you feel like it's worth the effort) - I had custom injection strategies in mind here :)

**Comment by timriley** [comment]
Ah, that's on my list anyway!

Still to-do:

- Custom injection strategies
- Working with existing classes

**Comment by vitaly-pushkar** [comment]
@solnic could you elaborate, please? What custom injection strategies are possible? I would like to extend the docs with an example but to be honest - can't think of any. `args`, `hash` and `kwargs` seem to be covering most use cases possible in Ruby.

**Comment by solnic** [comment]
@vitaly-pushkar we can skip it for now
